const mongoose = require('mongoose');

const schema = new mongoose.Schema({
  staffNo: { type: String },
  role: { type: String, default: 'Teacher' },
  firstName: { type: String, required: true },
  lastName: { type: String },
  fatherName: { type: String },
  email: { type: String   match: [/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/, 'Please enter a valid real email address']
  },
  phone: { type: String   match: [/^(((\+92)|(0092))-{0,1}\d{3}-{0,1}\d{7}$|^\d{11}$|^\d{4}-\d{7}$|^\+\d{10,15})$/, 'Please enter a valid phone number']
  },
  mobile: { type: String },
  emergencyMobile: { type: String },
  gender: { type: String },
  dateOfBirth: { type: String },
  dob: { type: String },
  dateOfJoining: { type: String },
  maritalStatus: { type: String },
  cnic: { type: String },
  cnicFront: { type: String },
  cnicBack: { type: String },
  qualificationLevel: { type: String },
  qualificationDocument: { type: String },
  document1: { type: String },
  currentAddress: { type: String },
  permanentAddress: { type: String },
  qualifications: { type: String },
  experience: { type: String },
  departmentId: { type: String },
  department: { type: String },
  designationId: { type: String },
  designation: { type: String },
  basicSalary: { type: Number },
  salary: { type: Number },
  allowances: { type: Number },
  deductions: { type: Number },
  bankName: { type: String },
  accountNo: { type: String },
  accountName: { type: String },
  branchName: { type: String },
  ifscCode: { type: String },
  photo: { type: String },
  staffPhoto: { type: String },
  facebook: { type: String },
  twitter: { type: String },
  linkedin: { type: String },
  instagram: { type: String },
  status: { type: String, default: 'Active' }
}, { timestamps: true });

module.exports = mongoose.model('Staff', schema);
